recipes-devtools/ssat/ssat_1.0.0.bb
Currently NNstreamer uses ssat to run the test cases. It is in the
recipes-devtools dir.
=> [SSAT] Add ssat to test nnstreamer

conf/layer.conf
Since meta-neural-network depends on meta-oe, it is required to increase priority of bb files more than 6, which is the priority of bb files in meta-oe.
1. Build test: [X]Passed [ ]Failed [*]Skipped
2. Run test: [X]Passed [ ]Failed [* ]Skipped
=> [Conf/Layer] Increase priority of bb files to 7

recipes-tensorflow/tensorflow-lite/files/apply-modification-for-tflite-1.12-to-eigen.patch, recipes-tensorflow/tensorflow-lite/files/tensorflow-lite.pc.in, recipes-tensorflow/tensorflow-lite/tensorflow-lite_1.12.bb
This patch adds a bitbake recipe for tensorflow lite v.1.12. Note that since this dev package contains header files from flatbuffers needed for using tensorflow lite v.1.12, it may create a conflict with another
flatbuffers package from other layers.
Related: https://github.com/nnsuite/nnstreamer/issues/1171
- V2
- Add -fPIC to CFLAGS, CPPFLAGS, CXXFLAGS
- Include missing header files
=> [TensorFlow] Add a bitbake recipe for TensorFlow Lite v.1.12 @open sesame 04/17 14:38

recipes-nnstreamer/nnstreamer/nnstreamer_0.1.2.bb
This patch adds a do_install_append task for creating a symbolic link in ${libdir} to ${libdir}/gstreamer-1.0/libnnstreamer.so.
2. Run test: [ ]Passed [ ]Failed [  ]Skipped
=> [Recipe/NNStreamer] Create symlink in ${libdir} to libnnstreamer.so

recipes-tensorflow/tensorflow-lite/tensorflow-lite_1.12.bb
For the convenience, this patch adds 'protocol' parameter with 'https' to SRC_URI in the bitbakse recipe for tensorflow-lite v.1.12.
=> [Recipe/TFLite] Add 'protocol' parameter with 'https' to SRC_URI

recipes-nnstreamer/nnstreamer/nnstreamer_0.1.2.bb
This patch extracts sub-plugin for tensorflow-lite from the main package and creates another package for it.
Epic: https://github.com/nnsuite/nnstreamer/issues/1005
Resolves: https://github.com/nnsuite/nnstreamer/issues/1171
2. Run test: [ ]Passed [ ]Failed [ ]Skipped
=> [Recipe/NNStreamer] Separate sub-plugin for tflite from the main package

recipes-tensorflow/tensorflow-lite/tensorflow-lite_1.12.bb
Since all the other sub-packages have a dependency on the main package, ${PN} which currently does not exist, bitbake fails when trying to install those sub-packages into rootfs using such  CORE_IMAGE_EXTRA_INSTALL like variables. In order to fix this issue, this patch creates the main
package containing nothing.
=> [Recipe/TFLite] bugfix: Create main package containing nothing

recipes-nnstreamer/nnstreamer/nnstreamer_0.1.2.bb
Disable pytorch for nnstreamer in yocto
1. Build test: [ ]Passed [ ]Failed [*]Skipped
2. Run test: [ ]Passed [ ]Failed [* ]Skipped
Signed-off-by: Parichay Kapoor <pk.kapoor@samsung.com>
=> [pytorch] Disable pytorch for nnstreamer @open sesame 05/22 10:50

recipes-nnstreamer/nnstreamer/nnstreamer_0.1.2.bb
This patch removes the license file, LICENSE.Apache-2.0, which is unused anymore, from LIC_FILES_CHKSUM.
=> [Recipe/NNStreamer] Remove unused license from LIC_FILES_CHKSUM @open sesame 6/04 09:15

recipes-nnstreamer/nnstreamer/files/0001-Test-Common-Remove-a-unit-test-for-custom-configurat.patch, recipes-nnstreamer/nnstreamer/nnstreamer_0.1.2.bb
This patch add a local patch for gstreamer to skip a unit test about custom configuration file provided by the environment variable.
=> [Recipe/NNStreamer] Add a local patch for skipping unsupported unit test

recipes-nnstreamer/nnstreamer/nnstreamer_0.1.2.bb
Since the build option for opencv is not supported anymore, this patch removes it from the bitbake recipe.
1. Build test: [ ]Passed [ ]Failed [*]Skipped
2. Run test: [ ]Passed [ ]Failed [* ]Skipped
=> [Recipe/NNStreamer] Remove build option control for OpenCV @open sesame 6/13 19:25

recipes-nnstreamer/nnstreamer/nnstreamer_0.2.0.bb
Related to https://github.com/nnsuite/nnstreamer/pull/1456
Although libnnstreamer.so is a shared object that required at runtime, this file is included in the dev package rather than the main package. This patch fixes this issue.
=> [Recipe/NNStreamer] Exclude libnnstreamer.so from dev package

recipes-nnstreamer/nnstreamer/nnstreamer_0.2.0.bb
Related to https://github.com/nnsuite/nnstreamer/pull/1456
This patch revises the bitbake file so that let the files related to those features be only installed when 'tensorflow-lite' is appened to the DISTRO_FEATURES variable.
=> [Recipe/NNStreamer] Use DISTRO_FEATURES to control TFLite related features @open sesame 7/25 07:24

recipes-nnstreamer/nnstreamer/nnstreamer_1.0.0.bb
This PR may fixes the failure in our system (#41). IMO, since only `zeus` provides meson > 0.50, to keep the version of NNStreamer as https://github.com/nnsuite/nnstreamer/releases/tag/v1.0.0 is the only way to stay in `warrior`.
Therefore, instead of using ${AUTOREV}, this patch modifies SRCREV to the latest stable version of NNStreamer, v1.0.0.
=> [Recipe/NNStreamer] Bump up the version of NNStreamer to 1.0.0

LICENSE
Added a notice that being a Apache-2.0 meta does not mean
that the packages included in this meta are licensed with
Apache 2.0.
Addresses #40
CC: @sagarsahu27 
Signed-off-by: MyungJoo Ham <myungjoo.ham@samsung.com>
=> [LICENSE] Add Apache 2.0 License @open sesame 10/25 11:45

recipes-devtools/ssat/ssat_1.0.0.bb
The upstream repository of SSAT has been changed so that this patch updates SRC_URI in the bitbake recipe as well.
2. Run test: [ ]Passed [ ]Failed [*]Skipped
=> [Recipe/DevTools/SSAT] Update SRC_URI to use upstream on git.tizen.org

conf/layer.conf, recipes-nnstreamer/nnstreamer/files/0001-Test-Common-Remove-a-unit-test-for-custom-configurat.patch, recipes-nnstreamer/nnstreamer/nnstreamer_1.5.3.bb
This patch bumps up the version of NNStreamer to v1.5.3 (v1.6.0-RC4). To this end, LAYERSERIES_COMPAT is revised to include 'zeus' instead of 'thud' and 'warrior' which do not support meson (>= v0.50). In addition, dependencies on Python 2.7 are also removed from the bitbake recipe.
Note that Dunfell (the first LTS release of Yocto project) will be also added to LAYERSERIES_COMPAT soon.
2. Run test: [*]Passed [ ]Failed [ ]Skipped
Build tests are done for qemu-x64 and qemu-arm64.
=> [Recipe/NNStreamer] Bump up to v1.5.3

recipes-tensorflow/tensorflow-lite/files/tensorflow-lite.pc.in, recipes-tensorflow/tensorflow-lite/tensorflow-lite_1.15.2.bb
To support nnstreamer, this PR includes the following patches:
- [Recipe/TFLite] Keep backward compatibility with v1.09
- NNStreamer uses tensorflow/contrib/lite/*.h to keep backward compatibility with v1.09. To this end, this patch creates a symlink to tensorflow/lite in tensorflow/contrib.
- [Recipe/TFLite] Add -lrt to the .pc template file for tf-lite 
- NnApi uses shm_open() so that the link option, -lrt, is required to build with the tensorflow-lite library. This patch fixes it by adding -lrt to the Libs field of the .pc template file.
Related to https://github.com/nnstreamer/nnstreamer/issues/2740 and https://github.com/nnstreamer/nnstreamer/issues/2732
2. Run test: [ ]Passed [ ]Failed [*]Skipped
Signed-off-by: Wook …
=> [Recipe/TFLite] Revise the bitbake recipe for TFLite 1.15.2 to support nnstreamer

lib/oeqa/runtime/cases/nnstreamer.py
OETestID has been dropped in OE-Core. In order to make the test script, nnstreamer.py, compatible with 'zeus', this patch removes the OETestID relevant code from the script.
See also: http://git.yoctoproject.org/cgit.cgi/poky/commit/?h=zeus&id=c7592b01478def091b6787412390c61e7ce0a0cd
Related to https://github.com/nnstreamer/nnstreamer/issues/2740 and https://github.com/nnstreamer/nnstreamer/issues/2732
2. Run test: [*]Passed [ ]Failed [ ]Skipped
=> [OEQA/NNStreamer] Drop OETestID

recipes-blas/openblas/files/0001-Modify-makefile-for-yocto.patch, recipes-blas/openblas/openblas_0.3.10.bb, recipes-nntrainer/nntrainer/files/0001-Patch-for-yocto-build.patch, recipes-nntrainer/nntrainer/nntrainer_0.1.1.bb
- Add recipes and patches for iniparser and openblas which nntrainer requires
- This recipe for nntrainer fetch the main branch of nntrainer.git and packaging it
- You could check the unittest binaries at `/usr/lib/nntrainer/bin/applications/unittest_*`
- TODO: Add package `nntrainer-application` and resolve deps
2. Run test: [*]Passed [ ]Failed [ ]Skipped
=> [Recipe/nntrainer] Add recipe for nntrainer

recipes-tensorflow/tensorflow-lite/tensorflow-lite_1.12.0.bb
- Rename 1.12 -> 1.12.0 so nnstreamer can fetch its micro version
- Update checksum and download link
=> [recipe/tflite] Fix build break in tflite_1.12

lib/oeqa/runtime/cases/nnstreamer.py
- After https://github.com/nnstreamer/nnstreamer/pull/2917 ,
All unittests pass
- Disable SSAT test temporarily : It takes too much time and need to be fixed for some cases
=> [oeqa/nnstreamer] Fix unittests and disable SSAT test

.github/CODEOWNERS
CODEOWNERS of github is very peaky (buggy) with formats.
Remove the trailing empty line.
Signed-off-by: MyungJoo Ham <myungjoo.ham@samsung.com>
=> CODEOWNERS: fix: remove trailing empty line.

recipes-devtools/ssat/ssat_1.0.0.bb, recipes-nnstreamer/nnstreamer/nnstreamer_1.7.2.bb
- Set proper branch name for ssat
- Fix recipe for nnstreamer:
remove unnecessary files tvm_*.so
disable pbtxt converter
change unittest path
=> [Fix] Fix recipes to be built

recipes-nnstreamer/nnstreamer/nnstreamer_2.1.0.bb
QA issue occurs for the nnstreamer on kirkstone. So it should be updated property. Refer to below license changes for the yocto kirkstone.
https://docs.yoctoproject.org/dev/migration-guides/migration-4.0.html#license-changes.
<ERROR Messages>
ERROR: nnstreamer-2.1.0+gitAUTOINC+b251e9bc6b-r0 do_package_qa: QA Issue: Recipe LICENSE includes obsolete licenses LGPLv2.1 [obsolete-license] ERROR: nnstreamer-2.1.0+gitAUTOINC+b251e9bc6b-r0 do_package_qa: Fatal QA errors were found, failing task.
---
In general, github system automatically copies your commit message for your convenience.
Please remove unused part of the template after writing your own PR description with this template.
```bash
$ git commit -s filename1 filename2 ... [enter]
Summarize changes in around 50 characters or less
More …
```
=> [nnstreamer] Fix the QA issue for the LICENSE on kirkstone
