lib/oeqa/runtime/cases/nnstreamer.py

Add python code to testimage. It run and check nnstreamer test codes
and libs.

[TESTIMAGE] Add python code for testimage

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md
.github/ISSUE_TEMPLATE/Support_request.md
.github/PULL_REQUEST_TEMPLATE.md

[GITHUB] Add github conf

---

lib/oeqa/runtime/cases/nnstreamer.py
recipes-nnstreamer/nnstreamer/nnstreamer_0.1.2.bb

In order to test nnstreamer after installation, we need install test
packages.

[UNITTEST] Modify unittest case installation

---

README.md

[README] Add meson dependency -@open sesame 04/08 10:36

---

conf/layer.conf
recipes-nnstreamer/nnstreamer/nnstreamer_0.1.2.bb

Make brief using PACKAGECONFIG and remove do_install_append

[UNITTEST] add opencv, tensorflow in PACKAGECONFIG @open sesame 04/10 10:40

---

recipes-devtools/ssat/ssat_1.0.0.bb

Add sysroot_stage_all_append to use ssat for test

[SSAT] add sysroot stage

---

conf/layer.conf
recipes-nnstreamer/nnstreamer/nnstreamer_0.1.2.bb

Extract unittest and make seperate package.

[UNITTEST] extract unittest and make seperate package  @open sesame 04/17 19:24

---

README.md
recipes-nnstreamer/nnstreamer/nnstreamer_0.1.2.bb

In this PR, 
- the bb recipe file for nnstreamer is modified to follow 'Format Guide' in Openembedded's Styleguide 
- README files is updated to exclude unnecessary dependencies and include required dependency
1. Build test: [ ]Passed [ ]Failed [*]Skipped
2. Run test: [ ]Passed [ ]Failed [* ]Skipped

Do formatting style of the bb recipe for nnstreamer and update README @open sesame 04/18 09:47

---

recipes-nnstreamer/nnstreamer/nnstreamer_0.1.2.bb

Add tensorflow-lite in DPENDS.

[TF-LITE] Add tensorflow-lite in DPENDS.

---

recipes-nnstreamer/nnstreamer/files/0001-Test-Common-Remove-a-unit-test-for-custom-configurat.patch
recipes-nnstreamer/nnstreamer/nnstreamer_0.2.0.bb

This patch updates the version of NNStreamer to 0.2.0.
**Changes in this PR**
- V2: Disable Caffe2
- V2: Update local patch
1. Build test: [ ]Passed [ ]Failed [*]Skipped
2. Run test: [ ]Passed [ ]Failed [* ]Skipped

[Recipe/NNStreamer] Update version to 0.2.0 @open sesame 6/13 19:24

---

README.md

In order to clarify license information of this project, this patch appends a disclaimer section to the README.md file.

[README] Append a disclaimer section to README 

---

recipes-tensorflow/tensorflow-lite/files/apply-modification-for-tflite-1.15-to-eigen.patch
recipes-tensorflow/tensorflow-lite/tensorflow-lite_1.15.2.bb

Adds tensorflow-lite_1.15.2.bb.

Add tensorflow-lite recipe for version 1.15.2. @open sesame 2/07 12:17

---

recipes-nnstreamer/nnstreamer/files/0001-Test-Common-Remove-a-unit-test-for-custom-configurat.patch
recipes-nnstreamer/nnstreamer/nnstreamer_1.5.3.bb

This patch revises the bitbake recipe to support up to date changes in NNStreamer:
- CPP custom filter support
- Keep consistency in PACKAGES, DEPENDS, and RPROVIDES fields for
TensorFlow-Lite Extension
- Rebase the local patch onto master
Related to https://github.com/nnstreamer/nnstreamer/issues/2732 and https://github.com/nnstreamer/nnstreamer/issues/2740

[Recipes/NNS] Revise the bitbake recipe for up to date changes

---

.github/CODEOWNERS
README.md
recipes-devtools/ssat/ssat_1.0.0.bb
recipes-nnstreamer/nnstreamer/nnstreamer_1.5.3.bb

- Add CODEOWNERS
- Fix urls: nnsuite -> nnstreamer
- Fix branch name: master -> main

[Trivial] Fix misc. urls and codeowners

---

recipes-nntrainer/nntrainer/files/0001-Patch-for-yocto-build.patch
recipes-nntrainer/nntrainer/nntrainer_0.1.1.bb

- Set newly added meson option for backbone to false
- Update patch file

[recipe/nntrainer] Fix build break in nntrainer

---

lib/oeqa/runtime/cases/nnstreamer.py
recipes-nnstreamer/nnstreamer/nnstreamer_1.7.0.bb

- Change `libnnstreamer_filter_tensorflow-lite` to `libnnstreamer_filter_tensorflow1-lite`
- Add `unittest_tizen_tensorflow_lite` and `unittest_tizen_tensorflow_lite-set`

[NNS] Fix tflite subplugin so name and add unittest for tflite subplugin

---

recipes-nnstreamer/nnstreamer/nnstreamer_1.7.0.bb

It's LGPL 2.1, not LGPL 2+. (2.1 only)
Signed-off-by: MyungJoo Ham <myungjoo.ham@samsung.com>

[NNStreamer] License declaration fix.

---

conf/layer.conf

Add recent series: funfell and gatesgarth.
Fixes #62
Signed-off-by: MyungJoo Ham <myungjoo.ham@samsung.com>

[Conf/Layer] Update supported Yocto series.

---

recipes-tensorflow/tensorflow-lite/tensorflow-lite_2.3.bb

---
In general, github system automatically copies your commit message for your convenience.
Please remove unused part of the template after writing your own PR description with this template.
```bash
$ git commit -s filename1 filename2 ... [enter]
Summarize changes in around 50 characters or less
More detailed explanatory text, if necessary. Wrap it to about 72
characters or so. In some contexts, the first line is treated as the
subject of the commit and the rest of the text as the body. The
blank line separating the summary from the body is critical;
various tools like `log`, `shortlog` and `rebase` can get confused 
if you run the two together.
Further paragraphs come after blank lines.
**Changes proposed in this PR:**
- Bullet points are okay, too
- Typically a hyphen or asterisk is …
```

Creates a recipe for tensorflow-lite 2.3

---

lib/oeqa/runtime/cases/nnstreamer.py
recipes-devtools/ssat/ssat_1.0.0.bb
recipes-nnstreamer/nnstreamer/nnstreamer_1.7.2.bb

This commit does:
- Add unittests for if, rate, tizen_capi, cppfilter
`$ bitbake core-image-minimal -c testimage`

[recipe/NNS] Add testcases

---

recipes-ml-api/ml-api/ml-api_1.7.2.bb
recipes-nnstreamer/nnstreamer/nnstreamer_1.7.2.bb

- Add recipe for ml-api:
source: github.com/nnstreamer/api.git
- Link /usr/lib/libnnstreamer.so -> /usr/lib/gstreamer-1.0.so

[recipe/ml-api] Add recipe for ml-api 

---

recipes-nnstreamer/nnstreamer/nnstreamer_2.1.0.bb

- Update the version of nnstreamer to 2.1.0

[receipe/nnstreamer] Update nnstreamer version to 2.1.0

---

recipes-nnstreamer/nnstreamer/nnstreamer_2.1.0.bb

- Add the new dependency of recent NNStreamer.

[nnstreamer] Add depedency json-glib
